CREATE TABLE INFORM
(
    ID bigint DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_12E23469_B819_4E16_952A_7735546CB9C6" AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOTIFIER bigint NOT NULL,
    RECEIVER bigint NOT NULL,
    OUTERID bigint NOT NULL,
    TYPE integer NOT NULL,
    GMT_CREATE bigint NOT NULL,
    STATUS integer DEFAULT 0 NOT NULL,
    INFORM_NAME varchar(100) NOT NULL,
    OUTER_TITLE varchar(200)
);
COMMENT ON COLUMN INFORM.NOTIFIER IS '发出通知的人';
COMMENT ON COLUMN INFORM.RECEIVER IS '接收通知的人';
COMMENT ON COLUMN INFORM.OUTERID IS '外键ID?';
COMMENT ON COLUMN INFORM.TYPE IS '通知类型';
COMMENT ON COLUMN INFORM.STATUS IS '0未读,1已读';
COMMENT ON COLUMN INFORM.INFORM_NAME IS '发出通知的人的用户名';
COMMENT ON COLUMN