package org.zyx.model;

public class Inform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORM.ID
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORM.NOTIFIER
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORM.RECEIVER
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORM.OUTERID
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORM.TYPE
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORM.GMT_CREATE
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORM.STATUS
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORM.INFORM_NAME
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    private String informName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORM.OUTER_TITLE
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORM.ID
     *
     * @return the value of INFORM.ID
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORM.ID
     *
     * @param id the value for INFORM.ID
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORM.NOTIFIER
     *
     * @return the value of INFORM.NOTIFIER
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORM.NOTIFIER
     *
     * @param notifier the value for INFORM.NOTIFIER
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORM.RECEIVER
     *
     * @return the value of INFORM.RECEIVER
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORM.RECEIVER
     *
     * @param receiver the value for INFORM.RECEIVER
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORM.OUTERID
     *
     * @return the value of INFORM.OUTERID
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORM.OUTERID
     *
     * @param outerid the value for INFORM.OUTERID
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORM.TYPE
     *
     * @return the value of INFORM.TYPE
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORM.TYPE
     *
     * @param type the value for INFORM.TYPE
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORM.GMT_CREATE
     *
     * @return the value of INFORM.GMT_CREATE
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORM.GMT_CREATE
     *
     * @param gmtCreate the value for INFORM.GMT_CREATE
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORM.STATUS
     *
     * @return the value of INFORM.STATUS
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORM.STATUS
     *
     * @param status the value for INFORM.STATUS
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORM.INFORM_NAME
     *
     * @return the value of INFORM.INFORM_NAME
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public String getInformName() {
        return informName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORM.INFORM_NAME
     *
     * @param informName the value for INFORM.INFORM_NAME
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public void setInformName(String informName) {
        this.informName = informName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORM.OUTER_TITLE
     *
     * @return the value of INFORM.OUTER_TITLE
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORM.OUTER_TITLE
     *
     * @param outerTitle the value for INFORM.OUTER_TITLE
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle;
    }
}