package org.zyx.repository;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.zyx.model.Inform;
import org.zyx.model.InformExample;

public interface InformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    long countByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    int deleteByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    int insert(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    int insertSelective(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    List<Inform> selectByExampleWithRowbounds(InformExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    List<Inform> selectByExample(InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    Inform selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Inform record, @Param("example") InformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFORM
     *
     * @mbg.generated Tue May 12 17:34:39 GMT+08:00 2020
     */
    int updateByPrimaryKey(Inform record);
}